namespace TallerMecanico
{
    partial class frmRefacciones
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmRefacciones));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            this.lblServicios = new System.Windows.Forms.Label();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtBuscar = new Bunifu.UI.WinForms.BunifuTextBox();
            this.materialPictureBox1 = new FontAwesome.Sharp.Material.MaterialPictureBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtIdRefaccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnLimpiar = new FontAwesome.Sharp.Material.MaterialButton();
            this.btnEliminar = new FontAwesome.Sharp.Material.MaterialButton();
            this.label1 = new System.Windows.Forms.Label();
            this.btnActualizar = new FontAwesome.Sharp.Material.MaterialButton();
            this.btnGuardar = new FontAwesome.Sharp.Material.MaterialButton();
            this.txtProveedor = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtStockMinimo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtStockActual = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPrecio = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMarca = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dgvRefacciones = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.materialPictureBox1)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvRefacciones)).BeginInit();
            this.SuspendLayout();
            // 
            // lblServicios
            // 
            this.lblServicios.AutoSize = true;
            this.lblServicios.Font = new System.Drawing.Font("Segoe UI Black", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblServicios.ForeColor = System.Drawing.Color.White;
            this.lblServicios.Location = new System.Drawing.Point(420, 17);
            this.lblServicios.Name = "lblServicios";
            this.lblServicios.Size = new System.Drawing.Size(371, 28);
            this.lblServicios.TabIndex = 2;
            this.lblServicios.Text = "ADMINISTRACIÓN DE REFACCIONES";
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(53)))), ((int)(((byte)(63)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.White;
            this.bunifuPanel2.BorderRadius = 15;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.txtBuscar);
            this.bunifuPanel2.Controls.Add(this.materialPictureBox1);
            this.bunifuPanel2.Location = new System.Drawing.Point(24, 12);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(358, 47);
            this.bunifuPanel2.TabIndex = 187;
            // 
            // txtBuscar
            // 
            this.txtBuscar.AcceptsReturn = false;
            this.txtBuscar.AcceptsTab = false;
            this.txtBuscar.AnimationSpeed = 200;
            this.txtBuscar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBuscar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBuscar.BackColor = System.Drawing.Color.Transparent;
            this.txtBuscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBuscar.BackgroundImage")));
            this.txtBuscar.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtBuscar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBuscar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtBuscar.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(53)))), ((int)(((byte)(63)))));
            this.txtBuscar.BorderRadius = 1;
            this.txtBuscar.BorderThickness = 1;
            this.txtBuscar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBuscar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBuscar.DefaultFont = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBuscar.DefaultText = "";
            this.txtBuscar.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(53)))), ((int)(((byte)(63)))));
            this.txtBuscar.HideSelection = true;
            this.txtBuscar.IconLeft = null;
            this.txtBuscar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBuscar.IconPadding = 10;
            this.txtBuscar.IconRight = null;
            this.txtBuscar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBuscar.Lines = new string[0];
            this.txtBuscar.Location = new System.Drawing.Point(45, 5);
            this.txtBuscar.MaxLength = 32767;
            this.txtBuscar.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBuscar.Modified = false;
            this.txtBuscar.Multiline = false;
            this.txtBuscar.Name = "txtBuscar";
            stateProperties1.BorderColor = System.Drawing.Color.White;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBuscar.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBuscar.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.White;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBuscar.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(53)))), ((int)(((byte)(63)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(53)))), ((int)(((byte)(63)))));
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBuscar.OnIdleState = stateProperties4;
            this.txtBuscar.Padding = new System.Windows.Forms.Padding(3);
            this.txtBuscar.PasswordChar = '\0';
            this.txtBuscar.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBuscar.PlaceholderText = "Buscar...";
            this.txtBuscar.ReadOnly = false;
            this.txtBuscar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBuscar.SelectedText = "";
            this.txtBuscar.SelectionLength = 0;
            this.txtBuscar.SelectionStart = 0;
            this.txtBuscar.ShortcutsEnabled = true;
            this.txtBuscar.Size = new System.Drawing.Size(291, 37);
            this.txtBuscar.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBuscar.TabIndex = 99;
            this.txtBuscar.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBuscar.TextMarginBottom = 0;
            this.txtBuscar.TextMarginLeft = 3;
            this.txtBuscar.TextMarginTop = 0;
            this.txtBuscar.TextPlaceholder = "Buscar...";
            this.txtBuscar.UseSystemPasswordChar = false;
            this.txtBuscar.WordWrap = true;
            this.txtBuscar.TextChange += new System.EventHandler(this.txtBuscar_TextChange);
            // 
            // materialPictureBox1
            // 
            this.materialPictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.materialPictureBox1.IconChar = FontAwesome.Sharp.MaterialIcons.Magnify;
            this.materialPictureBox1.IconColor = System.Drawing.Color.White;
            this.materialPictureBox1.IconSize = 37;
            this.materialPictureBox1.Location = new System.Drawing.Point(8, 6);
            this.materialPictureBox1.Name = "materialPictureBox1";
            this.materialPictureBox1.Size = new System.Drawing.Size(37, 37);
            this.materialPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.materialPictureBox1.TabIndex = 0;
            this.materialPictureBox1.TabStop = false;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.White;
            this.bunifuPanel1.BorderRadius = 20;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.txtIdRefaccion);
            this.bunifuPanel1.Controls.Add(this.btnLimpiar);
            this.bunifuPanel1.Controls.Add(this.btnEliminar);
            this.bunifuPanel1.Controls.Add(this.label1);
            this.bunifuPanel1.Controls.Add(this.btnActualizar);
            this.bunifuPanel1.Controls.Add(this.btnGuardar);
            this.bunifuPanel1.Controls.Add(this.txtProveedor);
            this.bunifuPanel1.Controls.Add(this.txtStockMinimo);
            this.bunifuPanel1.Controls.Add(this.txtStockActual);
            this.bunifuPanel1.Controls.Add(this.txtPrecio);
            this.bunifuPanel1.Controls.Add(this.txtMarca);
            this.bunifuPanel1.Controls.Add(this.txtNombre);
            this.bunifuPanel1.Location = new System.Drawing.Point(24, 84);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(358, 624);
            this.bunifuPanel1.TabIndex = 188;
            // 
            // txtIdRefaccion
            // 
            this.txtIdRefaccion.AcceptsReturn = false;
            this.txtIdRefaccion.AcceptsTab = false;
            this.txtIdRefaccion.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtIdRefaccion.AnimationSpeed = 200;
            this.txtIdRefaccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtIdRefaccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtIdRefaccion.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtIdRefaccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtIdRefaccion.BackgroundImage")));
            this.txtIdRefaccion.BorderColorActive = System.Drawing.Color.Orange;
            this.txtIdRefaccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtIdRefaccion.BorderColorHover = System.Drawing.Color.Silver;
            this.txtIdRefaccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtIdRefaccion.BorderRadius = 1;
            this.txtIdRefaccion.BorderThickness = 1;
            this.txtIdRefaccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtIdRefaccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIdRefaccion.DefaultFont = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtIdRefaccion.DefaultText = "";
            this.txtIdRefaccion.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtIdRefaccion.ForeColor = System.Drawing.Color.White;
            this.txtIdRefaccion.HideSelection = true;
            this.txtIdRefaccion.IconLeft = null;
            this.txtIdRefaccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIdRefaccion.IconPadding = 10;
            this.txtIdRefaccion.IconRight = null;
            this.txtIdRefaccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIdRefaccion.Lines = new string[0];
            this.txtIdRefaccion.Location = new System.Drawing.Point(17, 45);
            this.txtIdRefaccion.MaxLength = 32767;
            this.txtIdRefaccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtIdRefaccion.Modified = false;
            this.txtIdRefaccion.Multiline = false;
            this.txtIdRefaccion.Name = "txtIdRefaccion";
            stateProperties5.BorderColor = System.Drawing.Color.Orange;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIdRefaccion.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtIdRefaccion.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Silver;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIdRefaccion.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIdRefaccion.OnIdleState = stateProperties8;
            this.txtIdRefaccion.Padding = new System.Windows.Forms.Padding(3);
            this.txtIdRefaccion.PasswordChar = '\0';
            this.txtIdRefaccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtIdRefaccion.PlaceholderText = "Id";
            this.txtIdRefaccion.ReadOnly = false;
            this.txtIdRefaccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtIdRefaccion.SelectedText = "";
            this.txtIdRefaccion.SelectionLength = 0;
            this.txtIdRefaccion.SelectionStart = 0;
            this.txtIdRefaccion.ShortcutsEnabled = true;
            this.txtIdRefaccion.Size = new System.Drawing.Size(99, 44);
            this.txtIdRefaccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtIdRefaccion.TabIndex = 409;
            this.txtIdRefaccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtIdRefaccion.TextMarginBottom = 0;
            this.txtIdRefaccion.TextMarginLeft = 3;
            this.txtIdRefaccion.TextMarginTop = 0;
            this.txtIdRefaccion.TextPlaceholder = "Id";
            this.txtIdRefaccion.UseSystemPasswordChar = false;
            this.txtIdRefaccion.Visible = false;
            this.txtIdRefaccion.WordWrap = true;
            // 
            // btnLimpiar
            // 
            this.btnLimpiar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnLimpiar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(83)))), ((int)(((byte)(88)))));
            this.btnLimpiar.FlatAppearance.BorderSize = 0;
            this.btnLimpiar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLimpiar.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLimpiar.ForeColor = System.Drawing.Color.White;
            this.btnLimpiar.IconChar = FontAwesome.Sharp.MaterialIcons.Broom;
            this.btnLimpiar.IconColor = System.Drawing.Color.White;
            this.btnLimpiar.IconSize = 32;
            this.btnLimpiar.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLimpiar.Location = new System.Drawing.Point(195, 556);
            this.btnLimpiar.Name = "btnLimpiar";
            this.btnLimpiar.Size = new System.Drawing.Size(131, 44);
            this.btnLimpiar.TabIndex = 408;
            this.btnLimpiar.Text = "Limpiar";
            this.btnLimpiar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnLimpiar.UseVisualStyleBackColor = false;
            this.btnLimpiar.Click += new System.EventHandler(this.btnLimpiar_Click);
            // 
            // btnEliminar
            // 
            this.btnEliminar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnEliminar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(38)))), ((int)(((byte)(38)))));
            this.btnEliminar.Enabled = false;
            this.btnEliminar.FlatAppearance.BorderSize = 0;
            this.btnEliminar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnEliminar.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEliminar.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.IconChar = FontAwesome.Sharp.MaterialIcons.TrashCan;
            this.btnEliminar.IconColor = System.Drawing.Color.White;
            this.btnEliminar.IconSize = 32;
            this.btnEliminar.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEliminar.Location = new System.Drawing.Point(17, 556);
            this.btnEliminar.Name = "btnEliminar";
            this.btnEliminar.Size = new System.Drawing.Size(131, 44);
            this.btnEliminar.TabIndex = 407;
            this.btnEliminar.Text = "Eliminar";
            this.btnEliminar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnEliminar.UseVisualStyleBackColor = false;
            this.btnEliminar.Click += new System.EventHandler(this.btnEliminar_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Black", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(12, 14);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(195, 28);
            this.label1.TabIndex = 190;
            this.label1.Text = "Datos del Registro";
            // 
            // btnActualizar
            // 
            this.btnActualizar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnActualizar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(123)))), ((int)(((byte)(233)))));
            this.btnActualizar.Enabled = false;
            this.btnActualizar.FlatAppearance.BorderSize = 0;
            this.btnActualizar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnActualizar.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnActualizar.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.IconChar = FontAwesome.Sharp.MaterialIcons.Pencil;
            this.btnActualizar.IconColor = System.Drawing.Color.White;
            this.btnActualizar.IconSize = 32;
            this.btnActualizar.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnActualizar.Location = new System.Drawing.Point(195, 497);
            this.btnActualizar.Name = "btnActualizar";
            this.btnActualizar.Size = new System.Drawing.Size(131, 44);
            this.btnActualizar.TabIndex = 406;
            this.btnActualizar.Text = "Actualizar";
            this.btnActualizar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnActualizar.UseVisualStyleBackColor = false;
            this.btnActualizar.Click += new System.EventHandler(this.btnActualizar_Click);
            // 
            // btnGuardar
            // 
            this.btnGuardar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnGuardar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(144)))), ((int)(((byte)(92)))));
            this.btnGuardar.FlatAppearance.BorderSize = 0;
            this.btnGuardar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGuardar.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.IconChar = FontAwesome.Sharp.MaterialIcons.Floppy;
            this.btnGuardar.IconColor = System.Drawing.Color.White;
            this.btnGuardar.IconSize = 32;
            this.btnGuardar.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardar.Location = new System.Drawing.Point(17, 497);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.Size = new System.Drawing.Size(131, 44);
            this.btnGuardar.TabIndex = 405;
            this.btnGuardar.Text = "Guardar ";
            this.btnGuardar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnGuardar.UseVisualStyleBackColor = false;
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click);
            // 
            // txtProveedor
            // 
            this.txtProveedor.AcceptsReturn = false;
            this.txtProveedor.AcceptsTab = false;
            this.txtProveedor.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtProveedor.AnimationSpeed = 200;
            this.txtProveedor.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtProveedor.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtProveedor.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtProveedor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtProveedor.BackgroundImage")));
            this.txtProveedor.BorderColorActive = System.Drawing.Color.Orange;
            this.txtProveedor.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtProveedor.BorderColorHover = System.Drawing.Color.Silver;
            this.txtProveedor.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtProveedor.BorderRadius = 1;
            this.txtProveedor.BorderThickness = 1;
            this.txtProveedor.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtProveedor.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProveedor.DefaultFont = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtProveedor.DefaultText = "";
            this.txtProveedor.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtProveedor.ForeColor = System.Drawing.Color.White;
            this.txtProveedor.HideSelection = true;
            this.txtProveedor.IconLeft = null;
            this.txtProveedor.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProveedor.IconPadding = 10;
            this.txtProveedor.IconRight = null;
            this.txtProveedor.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProveedor.Lines = new string[0];
            this.txtProveedor.Location = new System.Drawing.Point(17, 411);
            this.txtProveedor.MaxLength = 32767;
            this.txtProveedor.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtProveedor.Modified = false;
            this.txtProveedor.Multiline = false;
            this.txtProveedor.Name = "txtProveedor";
            stateProperties9.BorderColor = System.Drawing.Color.Orange;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProveedor.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtProveedor.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Silver;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProveedor.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProveedor.OnIdleState = stateProperties12;
            this.txtProveedor.Padding = new System.Windows.Forms.Padding(3);
            this.txtProveedor.PasswordChar = '\0';
            this.txtProveedor.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProveedor.PlaceholderText = "Proveedor";
            this.txtProveedor.ReadOnly = false;
            this.txtProveedor.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtProveedor.SelectedText = "";
            this.txtProveedor.SelectionLength = 0;
            this.txtProveedor.SelectionStart = 0;
            this.txtProveedor.ShortcutsEnabled = true;
            this.txtProveedor.Size = new System.Drawing.Size(309, 44);
            this.txtProveedor.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtProveedor.TabIndex = 5;
            this.txtProveedor.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtProveedor.TextMarginBottom = 0;
            this.txtProveedor.TextMarginLeft = 3;
            this.txtProveedor.TextMarginTop = 0;
            this.txtProveedor.TextPlaceholder = "Proveedor";
            this.txtProveedor.UseSystemPasswordChar = false;
            this.txtProveedor.WordWrap = true;
            // 
            // txtStockMinimo
            // 
            this.txtStockMinimo.AcceptsReturn = false;
            this.txtStockMinimo.AcceptsTab = false;
            this.txtStockMinimo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtStockMinimo.AnimationSpeed = 200;
            this.txtStockMinimo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStockMinimo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStockMinimo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtStockMinimo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStockMinimo.BackgroundImage")));
            this.txtStockMinimo.BorderColorActive = System.Drawing.Color.Orange;
            this.txtStockMinimo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStockMinimo.BorderColorHover = System.Drawing.Color.Silver;
            this.txtStockMinimo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStockMinimo.BorderRadius = 1;
            this.txtStockMinimo.BorderThickness = 1;
            this.txtStockMinimo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStockMinimo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStockMinimo.DefaultFont = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtStockMinimo.DefaultText = "";
            this.txtStockMinimo.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtStockMinimo.ForeColor = System.Drawing.Color.White;
            this.txtStockMinimo.HideSelection = true;
            this.txtStockMinimo.IconLeft = null;
            this.txtStockMinimo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStockMinimo.IconPadding = 10;
            this.txtStockMinimo.IconRight = null;
            this.txtStockMinimo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStockMinimo.Lines = new string[0];
            this.txtStockMinimo.Location = new System.Drawing.Point(17, 345);
            this.txtStockMinimo.MaxLength = 32767;
            this.txtStockMinimo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStockMinimo.Modified = false;
            this.txtStockMinimo.Multiline = false;
            this.txtStockMinimo.Name = "txtStockMinimo";
            stateProperties13.BorderColor = System.Drawing.Color.Orange;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStockMinimo.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStockMinimo.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Silver;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStockMinimo.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStockMinimo.OnIdleState = stateProperties16;
            this.txtStockMinimo.Padding = new System.Windows.Forms.Padding(3);
            this.txtStockMinimo.PasswordChar = '\0';
            this.txtStockMinimo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtStockMinimo.PlaceholderText = "Stock minimo";
            this.txtStockMinimo.ReadOnly = false;
            this.txtStockMinimo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStockMinimo.SelectedText = "";
            this.txtStockMinimo.SelectionLength = 0;
            this.txtStockMinimo.SelectionStart = 0;
            this.txtStockMinimo.ShortcutsEnabled = true;
            this.txtStockMinimo.Size = new System.Drawing.Size(309, 44);
            this.txtStockMinimo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtStockMinimo.TabIndex = 4;
            this.txtStockMinimo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStockMinimo.TextMarginBottom = 0;
            this.txtStockMinimo.TextMarginLeft = 3;
            this.txtStockMinimo.TextMarginTop = 0;
            this.txtStockMinimo.TextPlaceholder = "Stock minimo";
            this.txtStockMinimo.UseSystemPasswordChar = false;
            this.txtStockMinimo.WordWrap = true;
            // 
            // txtStockActual
            // 
            this.txtStockActual.AcceptsReturn = false;
            this.txtStockActual.AcceptsTab = false;
            this.txtStockActual.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtStockActual.AnimationSpeed = 200;
            this.txtStockActual.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStockActual.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStockActual.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtStockActual.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStockActual.BackgroundImage")));
            this.txtStockActual.BorderColorActive = System.Drawing.Color.Orange;
            this.txtStockActual.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStockActual.BorderColorHover = System.Drawing.Color.Silver;
            this.txtStockActual.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStockActual.BorderRadius = 1;
            this.txtStockActual.BorderThickness = 1;
            this.txtStockActual.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStockActual.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStockActual.DefaultFont = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtStockActual.DefaultText = "";
            this.txtStockActual.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtStockActual.ForeColor = System.Drawing.Color.White;
            this.txtStockActual.HideSelection = true;
            this.txtStockActual.IconLeft = null;
            this.txtStockActual.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStockActual.IconPadding = 10;
            this.txtStockActual.IconRight = null;
            this.txtStockActual.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStockActual.Lines = new string[0];
            this.txtStockActual.Location = new System.Drawing.Point(17, 280);
            this.txtStockActual.MaxLength = 32767;
            this.txtStockActual.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStockActual.Modified = false;
            this.txtStockActual.Multiline = false;
            this.txtStockActual.Name = "txtStockActual";
            stateProperties17.BorderColor = System.Drawing.Color.Orange;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStockActual.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStockActual.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Silver;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStockActual.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStockActual.OnIdleState = stateProperties20;
            this.txtStockActual.Padding = new System.Windows.Forms.Padding(3);
            this.txtStockActual.PasswordChar = '\0';
            this.txtStockActual.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtStockActual.PlaceholderText = "Stock actual";
            this.txtStockActual.ReadOnly = false;
            this.txtStockActual.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStockActual.SelectedText = "";
            this.txtStockActual.SelectionLength = 0;
            this.txtStockActual.SelectionStart = 0;
            this.txtStockActual.ShortcutsEnabled = true;
            this.txtStockActual.Size = new System.Drawing.Size(309, 44);
            this.txtStockActual.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtStockActual.TabIndex = 3;
            this.txtStockActual.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStockActual.TextMarginBottom = 0;
            this.txtStockActual.TextMarginLeft = 3;
            this.txtStockActual.TextMarginTop = 0;
            this.txtStockActual.TextPlaceholder = "Stock actual";
            this.txtStockActual.UseSystemPasswordChar = false;
            this.txtStockActual.WordWrap = true;
            // 
            // txtPrecio
            // 
            this.txtPrecio.AcceptsReturn = false;
            this.txtPrecio.AcceptsTab = false;
            this.txtPrecio.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtPrecio.AnimationSpeed = 200;
            this.txtPrecio.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrecio.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrecio.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtPrecio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrecio.BackgroundImage")));
            this.txtPrecio.BorderColorActive = System.Drawing.Color.Orange;
            this.txtPrecio.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPrecio.BorderColorHover = System.Drawing.Color.Silver;
            this.txtPrecio.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPrecio.BorderRadius = 1;
            this.txtPrecio.BorderThickness = 1;
            this.txtPrecio.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrecio.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrecio.DefaultFont = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrecio.DefaultText = "";
            this.txtPrecio.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtPrecio.ForeColor = System.Drawing.Color.White;
            this.txtPrecio.HideSelection = true;
            this.txtPrecio.IconLeft = null;
            this.txtPrecio.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrecio.IconPadding = 10;
            this.txtPrecio.IconRight = null;
            this.txtPrecio.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrecio.Lines = new string[0];
            this.txtPrecio.Location = new System.Drawing.Point(17, 216);
            this.txtPrecio.MaxLength = 32767;
            this.txtPrecio.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrecio.Modified = false;
            this.txtPrecio.Multiline = false;
            this.txtPrecio.Name = "txtPrecio";
            stateProperties21.BorderColor = System.Drawing.Color.Orange;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrecio.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrecio.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Silver;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrecio.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrecio.OnIdleState = stateProperties24;
            this.txtPrecio.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrecio.PasswordChar = '\0';
            this.txtPrecio.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPrecio.PlaceholderText = "Precio unitario";
            this.txtPrecio.ReadOnly = false;
            this.txtPrecio.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrecio.SelectedText = "";
            this.txtPrecio.SelectionLength = 0;
            this.txtPrecio.SelectionStart = 0;
            this.txtPrecio.ShortcutsEnabled = true;
            this.txtPrecio.Size = new System.Drawing.Size(309, 44);
            this.txtPrecio.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtPrecio.TabIndex = 2;
            this.txtPrecio.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrecio.TextMarginBottom = 0;
            this.txtPrecio.TextMarginLeft = 3;
            this.txtPrecio.TextMarginTop = 0;
            this.txtPrecio.TextPlaceholder = "Precio unitario";
            this.txtPrecio.UseSystemPasswordChar = false;
            this.txtPrecio.WordWrap = true;
            // 
            // txtMarca
            // 
            this.txtMarca.AcceptsReturn = false;
            this.txtMarca.AcceptsTab = false;
            this.txtMarca.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtMarca.AnimationSpeed = 200;
            this.txtMarca.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMarca.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMarca.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtMarca.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMarca.BackgroundImage")));
            this.txtMarca.BorderColorActive = System.Drawing.Color.Orange;
            this.txtMarca.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMarca.BorderColorHover = System.Drawing.Color.Silver;
            this.txtMarca.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMarca.BorderRadius = 1;
            this.txtMarca.BorderThickness = 1;
            this.txtMarca.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMarca.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMarca.DefaultFont = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMarca.DefaultText = "";
            this.txtMarca.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtMarca.ForeColor = System.Drawing.Color.White;
            this.txtMarca.HideSelection = true;
            this.txtMarca.IconLeft = null;
            this.txtMarca.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMarca.IconPadding = 10;
            this.txtMarca.IconRight = null;
            this.txtMarca.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMarca.Lines = new string[0];
            this.txtMarca.Location = new System.Drawing.Point(17, 152);
            this.txtMarca.MaxLength = 32767;
            this.txtMarca.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMarca.Modified = false;
            this.txtMarca.Multiline = false;
            this.txtMarca.Name = "txtMarca";
            stateProperties25.BorderColor = System.Drawing.Color.Orange;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMarca.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMarca.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Silver;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMarca.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMarca.OnIdleState = stateProperties28;
            this.txtMarca.Padding = new System.Windows.Forms.Padding(3);
            this.txtMarca.PasswordChar = '\0';
            this.txtMarca.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMarca.PlaceholderText = "Marca";
            this.txtMarca.ReadOnly = false;
            this.txtMarca.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMarca.SelectedText = "";
            this.txtMarca.SelectionLength = 0;
            this.txtMarca.SelectionStart = 0;
            this.txtMarca.ShortcutsEnabled = true;
            this.txtMarca.Size = new System.Drawing.Size(309, 44);
            this.txtMarca.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtMarca.TabIndex = 1;
            this.txtMarca.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMarca.TextMarginBottom = 0;
            this.txtMarca.TextMarginLeft = 3;
            this.txtMarca.TextMarginTop = 0;
            this.txtMarca.TextPlaceholder = "Marca";
            this.txtMarca.UseSystemPasswordChar = false;
            this.txtMarca.WordWrap = true;
            // 
            // txtNombre
            // 
            this.txtNombre.AcceptsReturn = false;
            this.txtNombre.AcceptsTab = false;
            this.txtNombre.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtNombre.AnimationSpeed = 200;
            this.txtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombre.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombre.BackgroundImage")));
            this.txtNombre.BorderColorActive = System.Drawing.Color.Orange;
            this.txtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombre.BorderColorHover = System.Drawing.Color.Silver;
            this.txtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNombre.BorderRadius = 1;
            this.txtNombre.BorderThickness = 1;
            this.txtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNombre.DefaultText = "";
            this.txtNombre.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.txtNombre.ForeColor = System.Drawing.Color.White;
            this.txtNombre.HideSelection = true;
            this.txtNombre.IconLeft = null;
            this.txtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.IconPadding = 10;
            this.txtNombre.IconRight = null;
            this.txtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.Lines = new string[0];
            this.txtNombre.Location = new System.Drawing.Point(17, 89);
            this.txtNombre.MaxLength = 32767;
            this.txtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombre.Modified = false;
            this.txtNombre.Multiline = false;
            this.txtNombre.Name = "txtNombre";
            stateProperties29.BorderColor = System.Drawing.Color.Orange;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombre.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Silver;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnIdleState = stateProperties32;
            this.txtNombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombre.PasswordChar = '\0';
            this.txtNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombre.PlaceholderText = "Nombre";
            this.txtNombre.ReadOnly = false;
            this.txtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombre.SelectedText = "";
            this.txtNombre.SelectionLength = 0;
            this.txtNombre.SelectionStart = 0;
            this.txtNombre.ShortcutsEnabled = true;
            this.txtNombre.Size = new System.Drawing.Size(309, 44);
            this.txtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtNombre.TabIndex = 0;
            this.txtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombre.TextMarginBottom = 0;
            this.txtNombre.TextMarginLeft = 3;
            this.txtNombre.TextMarginTop = 0;
            this.txtNombre.TextPlaceholder = "Nombre";
            this.txtNombre.UseSystemPasswordChar = false;
            this.txtNombre.WordWrap = true;
            // 
            // dgvRefacciones
            // 
            this.dgvRefacciones.AllowCustomTheming = true;
            this.dgvRefacciones.AllowUserToAddRows = false;
            this.dgvRefacciones.AllowUserToDeleteRows = false;
            this.dgvRefacciones.AllowUserToResizeColumns = false;
            this.dgvRefacciones.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            this.dgvRefacciones.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvRefacciones.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dgvRefacciones.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvRefacciones.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.dgvRefacciones.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvRefacciones.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvRefacciones.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvRefacciones.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvRefacciones.ColumnHeadersHeight = 40;
            this.dgvRefacciones.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvRefacciones.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            this.dgvRefacciones.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvRefacciones.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.White;
            this.dgvRefacciones.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.dgvRefacciones.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            this.dgvRefacciones.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dgvRefacciones.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.dgvRefacciones.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dgvRefacciones.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvRefacciones.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvRefacciones.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            this.dgvRefacciones.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvRefacciones.CurrentTheme.Name = null;
            this.dgvRefacciones.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            this.dgvRefacciones.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvRefacciones.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.White;
            this.dgvRefacciones.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.dgvRefacciones.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvRefacciones.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvRefacciones.EnableHeadersVisualStyles = false;
            this.dgvRefacciones.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.dgvRefacciones.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dgvRefacciones.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvRefacciones.HeaderForeColor = System.Drawing.Color.White;
            this.dgvRefacciones.Location = new System.Drawing.Point(411, 84);
            this.dgvRefacciones.MultiSelect = false;
            this.dgvRefacciones.Name = "dgvRefacciones";
            this.dgvRefacciones.ReadOnly = true;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvRefacciones.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dgvRefacciones.RowHeadersVisible = false;
            this.dgvRefacciones.RowHeadersWidth = 51;
            this.dgvRefacciones.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.dgvRefacciones.RowTemplate.Height = 40;
            this.dgvRefacciones.RowTemplate.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvRefacciones.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvRefacciones.Size = new System.Drawing.Size(761, 624);
            this.dgvRefacciones.TabIndex = 407;
            this.dgvRefacciones.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Dark;
            this.dgvRefacciones.CellContentDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvRefacciones_CellContentDoubleClick);
            // 
            // frmRefacciones
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(35)))), ((int)(((byte)(43)))));
            this.ClientSize = new System.Drawing.Size(1184, 739);
            this.Controls.Add(this.dgvRefacciones);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.lblServicios);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmRefacciones";
            this.Text = "frmRefacciones";
            this.Shown += new System.EventHandler(this.frmRefacciones_Shown);
            this.bunifuPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.materialPictureBox1)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvRefacciones)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lblServicios;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtBuscar;
        private FontAwesome.Sharp.Material.MaterialPictureBox materialPictureBox1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtPrecio;
        private Bunifu.UI.WinForms.BunifuTextBox txtMarca;
        private Bunifu.UI.WinForms.BunifuTextBox txtProveedor;
        private Bunifu.UI.WinForms.BunifuTextBox txtStockMinimo;
        private Bunifu.UI.WinForms.BunifuTextBox txtStockActual;
        private FontAwesome.Sharp.Material.MaterialButton btnActualizar;
        private FontAwesome.Sharp.Material.MaterialButton btnGuardar;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvRefacciones;
        private FontAwesome.Sharp.Material.MaterialButton btnLimpiar;
        private FontAwesome.Sharp.Material.MaterialButton btnEliminar;
        private Bunifu.UI.WinForms.BunifuTextBox txtIdRefaccion;
    }
}